/**
 * Icon set (lucide). Deep imports keep the bundle and dev server lean.
 * Components take icons as `IconComponent` values so primitives stay icon-library agnostic.
 */
import type { JSX } from 'solid-js'
import type { LucideProps } from 'lucide-solid'

export type IconComponent = (props: LucideProps) => JSX.Element

export { default as AlertTriangle } from 'lucide-solid/icons/triangle-alert'
export { default as Check } from 'lucide-solid/icons/check'
export { default as ChevronDown } from 'lucide-solid/icons/chevron-down'
export { default as ChevronRight } from 'lucide-solid/icons/chevron-right'
export { default as ChevronUp } from 'lucide-solid/icons/chevron-up'
export { default as Cloud } from 'lucide-solid/icons/cloud'
export { default as CloudAlert } from 'lucide-solid/icons/cloud-alert'
export { default as CloudCheck } from 'lucide-solid/icons/cloud-check'
export { default as CloudOff } from 'lucide-solid/icons/cloud-off'
export { default as CloudUpload } from 'lucide-solid/icons/cloud-upload'
export { default as Download } from 'lucide-solid/icons/download'
export { default as Eraser } from 'lucide-solid/icons/eraser'
export { default as Eye } from 'lucide-solid/icons/eye'
export { default as EyeOff } from 'lucide-solid/icons/eye-off'
export { default as FileArchive } from 'lucide-solid/icons/file-archive'
export { default as FileSpreadsheet } from 'lucide-solid/icons/file-spreadsheet'
export { default as Folder } from 'lucide-solid/icons/folder'
export { default as FolderOpen } from 'lucide-solid/icons/folder-open'
export { default as FolderPlus } from 'lucide-solid/icons/folder-plus'
export { default as GripVertical } from 'lucide-solid/icons/grip-vertical'
export { default as Hand } from 'lucide-solid/icons/hand'
export { default as HardDrive } from 'lucide-solid/icons/hard-drive'
export { default as ImagePlus } from 'lucide-solid/icons/image-plus'
export { default as Images } from 'lucide-solid/icons/images'
export { default as Loader } from 'lucide-solid/icons/loader-circle'
export { default as Lock } from 'lucide-solid/icons/lock'
export { default as LockOpen } from 'lucide-solid/icons/lock-open'
export { default as Maximize } from 'lucide-solid/icons/maximize'
export { default as MoreHorizontal } from 'lucide-solid/icons/ellipsis'
export { default as PanelLeft } from 'lucide-solid/icons/panel-left'
export { default as Pencil } from 'lucide-solid/icons/pencil'
export { default as Pipette } from 'lucide-solid/icons/pipette'
export { default as Plus } from 'lucide-solid/icons/plus'
export { default as PlusCircle } from 'lucide-solid/icons/circle-plus'
export { default as Redo } from 'lucide-solid/icons/redo-2'
export { default as RefreshCw } from 'lucide-solid/icons/refresh-cw'
export { default as SlidersHorizontal } from 'lucide-solid/icons/sliders-horizontal'
export { default as Sparkles } from 'lucide-solid/icons/sparkles'
export { default as Trash } from 'lucide-solid/icons/trash'
export { default as Undo } from 'lucide-solid/icons/undo-2'
export { default as Upload } from 'lucide-solid/icons/upload'
export { default as X } from 'lucide-solid/icons/x'
export { default as ZoomIn } from 'lucide-solid/icons/zoom-in'
export { default as ZoomOut } from 'lucide-solid/icons/zoom-out'
export { default as Pointer } from 'lucide-solid/icons/pointer'
export { default as CircleDot } from 'lucide-solid/icons/circle-dot'
export { default as Circle } from 'lucide-solid/icons/circle'
export { default as Contrast } from 'lucide-solid/icons/contrast'
export { default as Info } from 'lucide-solid/icons/info'
export { default as CheckCircle } from 'lucide-solid/icons/circle-check'
export { default as AlertCircle } from 'lucide-solid/icons/circle-alert'
export { default as Microscope } from 'lucide-solid/icons/microscope'
export { default as LogOut } from 'lucide-solid/icons/log-out'
export { default as ArrowRightLeft } from 'lucide-solid/icons/arrow-right-left'
export { default as ChevronLeft } from 'lucide-solid/icons/chevron-left'
export { default as Keyboard } from 'lucide-solid/icons/keyboard'

import CircleIcon from 'lucide-solid/icons/circle'
import { mergeProps } from 'solid-js'
/** Solid filled circle (the "filled dot" marker style). */
export const CircleFilled: IconComponent = (props) => CircleIcon(mergeProps(props, { fill: 'currentColor' }))
export { default as Settings } from 'lucide-solid/icons/settings'
export { default as Volume2 } from 'lucide-solid/icons/volume-2'
